#parameters:
#    app.path.images: /public/images

vich_uploader:
    db_driver: orm

    mappings:
        souvenirs:
            uri_prefix: /images #Dossier d'arrivée des images (attributs des souvenirs)
            upload_destination: '%kernel.project_dir%/public/images'
